apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb_gateway
    type: influxdb
    access: proxy          # Grafana server kết nối tới InfluxDB (không phải browser)
    url: http://influxdb:8086
    jsonData:
      version: Flux        # Dùng ngôn ngữ Flux (không phải InfluxQL cũ)
      organization: iot-org
      defaultBucket: smart-building
    secureJsonData:
      token: my-super-secret-token
    isDefault: true        # Đây là datasource mặc định
    editable: true
